language: csharp
os: linux
dist: trusty
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
        - FrameworkPathOverride=/usr/lib/mono/4.6.1-api
dotnet: 2.0.0
mono: 5.2.0
script:
    - dotnet build
    - dotnet test SvgBuild.Tests
