language: csharp
os: linux
dist: trusty
mono: 5.4.1
install:
    - nuget restore
script:
    - msbuild /p:Configuration=Release SvgBuild.sln
    - mono packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe SvgBuild.Tests/bin/Release/SvgBuild.Tests.dll
    # Integration testing.
    # First update NuGet because the version installed on Travis is too old:
    - mkdir .nuget
    - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/v4.4.1/nuget.exe
    # Now pack the package:
    - mono .nuget/nuget.exe pack SvgBuild.MsBuild/SvgBuild.MsBuild.csproj -Tool -Prop Platform=AnyCPU -Prop Configuration=Release -MSBuildPath /usr/lib/mono/msbuild/15.0/bin/
    # Install the package:
    - cd SvgBuild.MsBuild.IntegrationTest
    - mkdir NuGetRepository
    - mono ../.nuget/nuget.exe add ../SvgBuild.MsBuild.0.0.1.nupkg -Source NuGetRepository
    - mono ../.nuget/nuget.exe restore -Source $PWD/NuGetRepository -PackagesDirectory packages
    # Check if the build works now:
    - msbuild /p:Platform=AnyCPU /p:Configuration=Release
    - '[ -e bin/Release/Test.bmp ] || exit 1'
    - '[ -e bin/Release/Test.ico ] || exit 1'
