language: csharp
os: linux
dist: trusty
mono: 5.4.1
install:
    - nuget restore
script:
    - msbuild /p:Configuration=Release SvgBuild.sln
    - mono packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe SvgBuild.Tests/bin/Release/SvgBuild.Tests.dll
