os: Visual Studio 2017
platform: Any CPU
skip_branch_with_pr: true
configuration: Release
before_build:
    - nuget restore
after_build:
    - packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.exe SvgBuild.Tests\bin\Release\SvgBuild.Tests.dll
    # Integration tests:
    - dir SvgBuild.MsBuild\bin\Release
    - nuget pack SvgBuild.MsBuild\SvgBuild.MsBuild.csproj -Tool -Prop Platform=AnyCPU -prop Configuration=Release
    - cd SvgBuild.MsBuild.IntegrationTest
    - mkdir NuGetRepository
    - nuget add ..\SvgBuild.MsBuild.0.0.1.nupkg -Source NuGetRepository
    - nuget restore -Source %cd%\NuGetRepository -PackagesDirectory packages
    - msbuild /p:Platform=AnyCPU /p:Configuration=Release
    - if not exist bin\Release\Test.bmp exit 1
