os: Visual Studio 2017
platform: Any CPU
skip_branch_with_pr: true
configuration: Release
environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
    - dotnet build
test_script:
    - dotnet test SvgBuild.Tests
