name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6'

jobs:
  main-windows:
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.*

      - name: Build
        run: dotnet build

      - name: Test (Windows)
        run: dotnet test
        if: matrix.os == 'windows-latest'

      - name: Test (Linux, Mono)
        run: mono ${{ github.workspace }}/.github/nuget-packages/xunit.runner.console/2.3.1/tools/net452/xunit.console.exe SvgBuild.Tests/bin/Debug/net461/SvgBuild.Tests.dll

      - name: Test (Linux, Integration)
        run: cd SvgBuild.MsBuild.IntegrationTests && dotnet test
