name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6'

jobs:
  main-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NuGet restore
        run: nuget restore

      - name: Discover MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild /p:Configuration=Release SvgBuild.sln

      - name: Test
        run: dotnet test

      - name: Integration test
        shell: pwsh
        run: SvgBuild.MsBuild.IntegrationTest\Run-IntegrationTest.ps1

  main-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NuGet restore
        run: nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release SvgBuild.sln

      - name: Test
        run: dotnet test

      - name: Integration test
        shell: pwsh
        run: SvgBuild.MsBuild.IntegrationTest/Run-IntegrationTest.ps1
